# Generated by Django 6.0.6 on 2026-06-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('Oil Change', 'Oil Change'), ('Water Wash', 'Water Wash'), ('General Service', 'General Service'), ('Brake Service', 'Brake Service')], max_length=50),
        ),
    ]
